/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyMain */

#ifndef _Included_MyMain
#define _Included_MyMain
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
